target 'Todo-Assignment' do
  use_frameworks!

  pod 'Realm'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'KeychainAccess'
  pod 'SVProgressHUD'

  target 'Todo-AssignmentTests' do
    inherit! :search_paths
  end

end
