# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo-Assignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Realm'
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift'
  pod 'SVProgressHUD'
  #pod 'SwiftyStarRatingView'

  target 'Todo-AssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
